### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/selected_face/face_emotion/relative_train_NCEV.txt'

### ISSUE THREAD

**Issue by sjghh** [ZebangCheng/Emotion-LLaMA#11]
作者您好我在复现代码的 Training的过程中遇到了，FileNotFoundError: [Errno 2] No such file or directory: '/home/user/selected_face/face_emotion/relative_train_NCEV.txt'的问题，另外，我想问一下在train的过程中，需要哪些数据需要放在那个位置，我在readme中没有找到，非常希望能得到您的帮助！

**Comment by ZebangCheng** [comment]
感谢你对我们工作的关注！


你可以通过以下Google Drive链接下载我们开源测试集的特征文件以进行简单复现。如果你需要完整的视频样本，请向[MER2023](http://merchallenge.cn/datasets)官方申请数据集：
```
https://drive.google.com/file/d/1DJJ8wP3g4yLT0ZFZ_-H4izJHAGJx2AJ_/view?usp=sharing
https://drive.google.com/file/d/1YyoWabWtAJuFI6ylMM220i_kh_0Nagv9/view?usp=sharing
```

你可以参考之前相关的issues，解决你可能遇到的大部分疑问(relative_train_NCEV.txt的文件链接以及文件含义等问题)：
```
https://github.com/ZebangCheng/Emotion-LLaMA/issues/2  
https://github.com/ZebangCheng/Emotion-LLaMA/issues/6  
```

如果你对视频处理和特征提取有兴趣，建议你参考[MER2023](https://github.com/CASIA-Affective-Computing-Group/MER2023-Baseline)和[MER2024](https://github.com/zeroQiaoba/MERTools/tree/master/MER2024)的项目仓库。

**Comment by crinoiddream** [comment]
作者您好，非常感谢您google分享的relative_test3_NCEV.txt，但是我没有找到relative_train_NCEV.txt，请问可以分享一下吗

**Comment by ZebangCheng** [comment]
> https://drive.google.com/file/d/17SO5S50wQPR42ernNsFwZM4wJQ0PDoNy/view?usp=sharing
