### ISSUE TITLE
关于峰值帧的选取疑惑

### ISSUE THREAD

**Issue by qq1332427275** [ZebangCheng/Emotion-LLaMA#12]
作者您好！您的论文中提到在构建数据集时，对峰值帧选择上，使用对各个帧的AU求和，进而找到最大值对应的帧，作为峰值帧，而在附录的A.3 Instruction Collection and Multimodal Annotation中，又提到使用最频繁出现的AU，然后对其幅度值求和，找到幅度最高的作为峰值帧，这两种方式是分别使用在不同时期吗？感谢您的阅读，期待您的回复！祝您一切顺利！

**Comment by ZebangCheng** [comment]
感谢你对我们工作的关注！

我们在构造数据集时，都是根据各个帧的AU求和，进而找到最大值对应的帧，作为峰值帧。根据AU从所有帧中找出最具有代表性的帧，以及对应的表情描述。

抱歉给你带来的困惑，我们将在后续的版本中阐述清楚。

**Comment by qq1332427275** [comment]
你好~还有一个小疑惑，目前检测AU为什么都使用Openface呢？很多在AU任务上准确率高的模型为什么不被使用呢？是因为Openface泛化能力更高一些吗？

**Comment by ZebangCheng** [comment]
首先，OpenFace 因其较高的知名度，通常成为在 AU 检测任务中的首选工具。其次，它的功能非常完善，可以直接从视频中检测并裁剪人脸，大大简化了 AU 检测的流程。最后，OpenFace 的操作相对简单，易于上手。

当然，也有一些在 AU 任务上表现更为优异的模型，只是它们的知名度可能不如 OpenFace 高。可以考虑探索一下这些最新的研究成果，看是否能够帮助提升模型性能。

**Comment by ZebangCheng** [comment]
我们在文章中的table 9中展示了用于生成多模态描述内容的上下文 prompt例子，包括System，Question。

**Comment by qq1332427275** [comment]
看到了此方面的内容，但我还想进一步学习，您能提供关于对audio提取和视觉部分使用的minigpt的prompt吗？十分感谢您的回复！

**Comment by qq1332427275** [comment]
了解了！请问您是否尝试过直接对音频使用详细描述的prompt呢？类似于”Please concisely analyze the emotions in this audio and summarize it ”？之类的方式？效果会更差吗

**Comment by qq1332427275** [comment]
还有个小问题就是您在提取视频峰值帧的AU时，是先将视频中的人脸提取，得到人脸图片后再得到图片的AU的吗，那部分数据集中有多个人脸时该如何处理呢？还有就是您对unlabel数据集的过滤是根据什么呢？除了均衡样本类别外，还有什么其他条件吗？十分感谢您！

**Comment by ZebangCheng** [comment]
1.是的，使用OpenFace可以直接输入视频得到不同帧提取好的人脸和AU信息。
2.我们使用的数据集的样本几乎全是单个人物，所以没有考虑过多个人脸时该如何处理。
3.先给无标签样本的一个伪标签，判断伪标签与对应AU信息是否匹配（happy => [“AU06”, “AU12”, “AU14”]); 然后使用大模型llama-3或者ChatGPT组合视觉，音频和文本线索，如果大模型输出线索直接有冲突，就把对应的样本筛选掉。

**Comment by qq1332427275** [comment]
了解了解！十分感谢您百忙之中的回复，但我还有以下疑惑，您的回复对我的帮助很大，祝您中秋佳节快乐！一切顺利！
> 了解了！请问您是否尝试过直接对音频使用详细描述的prompt呢？类似于”Please concisely analyze the emotions in this audio and summarize it ”？之类的方式？效果会更差吗

**Comment by ZebangCheng** [comment]
中秋节快乐！

qq1332427275 ***@***.***> 于2024年9月16日周一 12:01写道：

**Comment by qq1332427275** [comment]
我还有一个疑问您好像没有看见，
您是否尝试过直接对音频使用详细描述的prompt呢？类似于”Please concisely analyze the emotions
 in this audio and summarize it ”？之类的方式？效果会更差吗？
我最近在进行这部分工作，所以很期待您的答案！

**Comment by ZebangCheng** [comment]
一开始尝试的就是类似”Please concisely analyze the emotions in this audio and summarize it ”的prompt，个人感觉输出的音频描述效果较差。  

我使用的是ASR提取的中文字幕，具体的代码可以参考MER2023 baseline中的generate_transcription_files_asr()和refinement_transcription_files_asr()函数。
> https://github.com/CASIA-Affective-Computing-Group/MER2023-Baseline/blob/master/main-baseline.py

在后面的工作中也尝试使用QWen-Audio模型提取中文字幕，个人感觉效果差不多，准确的提高了一点点。提取中文字幕后，使用百度翻译API翻译为英语。

**Comment by qq1332427275** [comment]
请问您在文章中对encoder的消融实验是如何实现的呢？每个encoder的消融均是单独预训练再微调得到的结果吗，比如只有audio encoder时，也是只有audio encoder进行预训练，再进而微调得到的结果吗？

**Comment by ZebangCheng** [comment]
嗯嗯，是的，每个encoder的消融都是单独训练的。比如在audio encoder，就只加载了audio encoder的特征，而其他encoder的特征就设置为0向量。

**Comment by qq1332427275** [comment]
您好，请问您有公开pretrain的yaml文件吗，我目前只看见了finetune的yaml文件，如果公开了请告诉我，十分感谢您！

**Comment by qq1332427275** [comment]
还有一个疑惑想向您请教，您使用encoder的倒数第二层得到的feature作为输入，而使用encoder的最后一层得到的token作为llm的输入，这两种方式有什么区别吗？您是否尝试过将token作为输入呢？因为我对此没有细致的研究，期待您的解答，十分感谢！

**Comment by ZebangCheng** [comment]
> 还有一个疑惑想向您请教，您使用encoder的倒数第二层得到的feature作为输入，而使用encoder的最后一层得到的token作为llm的输入，这两种方式有什么区别吗？您是否尝试过将token作为输入呢？因为我对此没有细致的研究，期待您的解答，十分感谢！

抱歉。我没有理解这个问题的含义，能重新解释一下你的问题吗？这个工作的所有encoder都是使用使用encoder的最后一层得到的feature作为llm的输入。你能告诉我你说的倒数第二层得到的feature或者token指的是什么？

**Comment by qq1332427275** [comment]
ok，我可能描述的不是很准确，十分抱歉！我的意思是您现在的video、audio特征是来自于vision encoder的输出层前一层，也是它的最后一层，每个视频样本对应的维度可能是（3，1024）（三个encoder拼接后），而比如llava使用的是vision encoder最后一层后的token输出，比如是（576，1024），代表有576个token进入了llm。
请问您有尝试过使用上述类似token输入给llm的结果吗？这两种方式有何区别呢？期待您的回复~

**Comment by ZebangCheng** [comment]
我们提取的所有特征都是来自于Encoder的最后一层，我们对不同的特征进行处理，所以有些特征的维度变成了[1, 1024].   

我们一共包含4个Encoder: Audio, Temporal, Local, Global. 
- Audio Encoder最后输出维度是根据输入audio的长度所变化的[n, 1024]，我们参考之前的工作，对最后一层特征进行mean的操作，最终维度就是[1*1024]
- Local Encoder最后输出维度是固定的，假设是[576, 1024] + [1, 1024](class token), 我们最终使用的特征就是最后一层的class token。Temporal同理。
- Global Encoder的最后一层的维度是[1025, 1408]，为了保留所有背景信息提取全局特征，我们使用了所有token，首先将其划分为[1024, 1408] + [1, 1408](class token)。然后为了节约空间，将[1024, 1408]按4个一组转化为[256, 5632]。

以上所有的特征的都会经过映射层，转化为统一的维度4096，最终输入到llm的token数量如下：
Audio Encoder[1, 4096] +Temporal Encoder[1, 4096] + Local Encoder[1, 4096]  + Global Encoder[1, 4096]-[256, 4096] + Instruction Token[x, 4096] 

具体的实现可以参考我们的项目代码。

**Comment by xiaoyaoxinyi** [comment]
您好，我使用openface提取特征的时候，发现有一些AU是有值的，有一些AU是会用0和1判断存不存在，我想知道您在选择峰值帧的时候是使用前者的和还是所有的AU的和呢，谢谢您

**Comment by xiaoyaoxinyi** [comment]
了解了，谢谢您。在论文中我还有一个疑问，就是在构建数据集的时候，一个AU对应了多个不同的文本描述，我想询问一下如果我的峰值帧存在这个AU，AU映射的时候是对于不同的文本描述随机选择一个吗

**Comment by ZebangCheng** [comment]
> 了解了，谢谢您。在论文中我还有一个疑问，就是在构建数据集的时候，一个AU对应了多个不同的文本描述，我想询问一下如果我的峰值帧存在这个AU，AU映射的时候是对于不同的文本描述随机选择一个吗

是的。AU映射是随机选取一个对应的面部表情描述。

**Comment by qq1332427275** [comment]
作者您好，我在代码中看到您输入给llm时的token包括EVA的cls token、pool后的全局token、还有各个encoder得到的cls token，而源码中貌似只有EVA pool厚的全局token，为什么还需要加一个cls token呢？是尝试过对有提升吗？十分感谢您！

**Comment by ZebangCheng** [comment]
> 作者您好，我在代码中看到您输入给llm时的token包括EVA的cls token、pool后的全局token、还有各个encoder得到的cls token，而源码中貌似只有EVA pool厚的全局token，为什么还需要加一个cls token呢？是尝试过对有提升吗？十分感谢您！

1.刚开始我们的模型设计是不同的Encoder都提取一个一维的特征。cls token代表综合的特征，所以在项目初期，使用的是EVA的cls token作为全局特征输入到LLM中。  

2.在实验中，加入EVA的cls token是有效的，能够提升多模态融合的分数。  

3.但是早期的实验中，整体的分数都较低，不符合预期。经过我们团队的尝试，发现保留保留EVA的全部patch token，模型可以收敛的更快，效果更好。我们认为这样做，保留原有大模型的世界知识，然后在训练大模型情绪推理时就效果提升显著。  

4.所以，我们是觉得两部分都是有效的，就自然的将两部分代码结合起来。最终我们同时输入了EVA的patch token和cls token作为情绪理解的全局特征。  

5.源码中，因为要节约开销，将EVA的patch token每4个做一个合并，所以就余了一个cls token不用。

**Comment by qq1332427275** [comment]
作者你好~关于MERR数据集部分有个问题就是我查看您的coarse_grained.json，有部分文件我在MER2023的数据集里找不到，比如这个文件：
![image](https://github.com/user-attachments/assets/6058d904-5b6d-45cd-8665-bd5703616bc7)
这个文件是在哪里呢？十分感谢~

**Comment by ZebangCheng** [comment]
你MER2023的数据全部下载了吗？MER2023-SEMI对应的数量是7万多个视频。

sample_00000003对应的标注和视频截图如下：
```
    "sample_00000003": {
        "AU_list": [
            "AU12",
            "AU14"
        ],
        "visual_prior_list": [
            "Toothy smile",
            "Indentation when smiling"
        ],
        "audio_prior_list": "speaks in a normal tone.",
        "pseu_emotion": "happy",
        "caption": "Toothy smile, Indentation when smiling, speaks in a normal tone."
    },
```
![sample_00000003](https://github.com/user-attachments/assets/864b530d-0e39-40d9-b52b-b7e4ba157de4)

**Comment by qq1332427275** [comment]
我发现其他的视频我都找到了，但是这一个视频我没有找到，您方便把这一个视频发给我吗QAQ，十分感谢，我的邮箱：huazeyu666@nenu.edu.cn

**Comment by ZebangCheng** [comment]
> 我发现其他的视频我都找到了，但是这一个视频我没有找到，您方便把这一个视频发给我吗QAQ，十分感谢，我的邮箱：[huazeyu666@nenu.edu.cn](mailto:huazeyu666@nenu.edu.cn)

已经发送sample_00000003.avi。为了后续方便，还是检查一下你们下载的数据集与官方paper上的数量是否对应。

**Comment by qq1332427275** [comment]
你好，不好意思又来打扰您，关于各个模态的encoder预训练时，您是如何操作的呢？比如视频的mae模型，您将其在哪个数据集进行预训练呢？
比如在mllm的第一阶段也就是预训练阶段，使用MERR数据集的粗粒度数据，此时对于视频数据的特征已经通过预训练的mae和其他模型进行提取，这时的mae模型是在哪里训练过了呢？MERR数据集上吗？（然后根据分类效果最优的checkpoints进行得到各个视频的特征输入mllm进行预训练吗？）
在微调时呢？根据细粒度数据重新预训练了各个encoder吗？还有问题就是对下游的DFEW等数据集是在与细粒度的MERR一同微调训练的吗？因为DFEW等数据集没有细粒度描述，仅情感标签
因为我也在研究相关内容，希望得到您的细致实验细节，十分感谢您！

**Comment by qq1332427275** [comment]
了解，也就是encoder经过在MER2023-SEMI预训练后，在后续提取任何一个数据集时都没有重新训练过。
除此之外，在对每个下游数据集测试时，都是先对对应训练集微调，再进行测试，比如对DFEW做测试时，仅拿DFEW训练集进行微调，以此类推是吗

**Comment by ZebangCheng** [comment]
1. 是的，ncoder经过在MER2023-SEMI预训练后，在后续提取任何一个数据集时都没有重新训练过。
2. 是的，对每个下游数据集测试时，都是先对对应训练集微调，再进行测试。你的理解是正确的。

**Comment by qq1332427275** [comment]
你好，请问关于模型训练，在各个阶段您使用了多少个epoch呢？能否提供一下对应的loss数据文件呢？因为我自己在使用细粒度的MERR数据集训练时，loss下降的不是很多，且只训练了一个epoch，不知是否需要多轮训练？
并且在对下游数据集比如DFEW评估时，您是使用了多次epoch训练吗，一次epoch评估一次保留最优时的checkpoints？还是什么方式呢？十分感谢

**Comment by ZebangCheng** [comment]
> 你好，请问关于模型训练，在各个阶段您使用了多少个epoch呢？能否提供一下对应的loss数据文件呢？因为我自己在使用细粒度的MERR数据集训练时，loss下降的不是很多，且只训练了一个epoch，不知是否需要多轮训练？ 并且在对下游数据集比如DFEW评估时，您是使用了多次epoch训练吗，一次epoch评估一次保留最优时的checkpoints？还是什么方式呢？十分感谢

在两个阶段都是使用30个epoch. 对于下游任务也是训练了30个epoch，每一个epoch评估一次保留最优的checkpoints。

**Comment by qq1332427275** [comment]
了解了！可以麻烦您提供一下各个阶段包括（粗粒度细粒度和下游任务）的训练loss记录吗？
因为我这边使用粗粒度训练了一个epoch时loss最终下降到稳定在0.2左右，您认为是否有必要增加一些epoch训练呢？
细粒度训练一个epoch后loss却在1.2左右稳定，不再下降，我在尝试在细粒度增加一些epoch训练。十分感谢您的经验！

**Comment by ZebangCheng** [comment]
只训练了一个epoch后loss就到0.2确实效果挺好，你是使用了多张显卡吗？是加载了我们开源的模型参数进行训练的？训练了多个任务还是只有情绪识别任务？不同的设置，loss下降的不同。建议多训几个epoch保存模型进行测试，选择最优的模型参数进行下一步训练。

日志文件已上传：
> https://drive.google.com/drive/folders/1fP6UAuHMTZC-J8eTHI1I41UoPqhYjcSA?usp=sharing

**Comment by qq1332427275** [comment]
十分感谢您！对的，我是使用了8卡，目前在尝试使用其他的模型在您构建的数据集上进行训练，coarse-grained阶段的训练即使用了情感标签也进行了captain的推理，训练了一个epoch得到loss稳定在0.2附近。目前正在对fine-grained进行多轮epoch训练（也是使用细粒度的captain和情感标签两个任务），您提到使用最优的模型参数是指loss最低时的模型参数进行下一阶段训练吗？
如果我后续要对DFEW等下游数据集进行训练并评估，对有多个交叉验证的数据集，您是如何训练的呢？比如论文中对DFEW数据集得到的指标是在5个set上分别训练并测试得到的结果进行平均的吗？具体来说，在5个set的train数据上分别训练了30个epoch，对每个set找到最优的test数据上的指标，最终对5个指标平均的结果吗？十分期待您的回复~

**Comment by ZebangCheng** [comment]
> 十分感谢您！对的，我是使用了8卡，目前在尝试使用其他的模型在您构建的数据集上进行训练，coarse-grained阶段的训练即使用了情感标签也进行了captain的推理，训练了一个epoch得到loss稳定在0.2附近。目前正在对fine-grained进行多轮epoch训练（也是使用细粒度的captain和情感标签两个任务），您提到使用最优的模型参数是指loss最低时的模型参数进行下一阶段训练吗？ 如果我后续要对DFEW等下游数据集进行训练并评估，对有多个交叉验证的数据集，您是如何训练的呢？比如论文中对DFEW数据集得到的指标是在5个set上分别训练并测试得到的结果进行平均的吗？具体来说，在5个set的train数据上分别训练了30个epoch，对每个set找到最优的test数据上的指标，最终对5个指标平均的结果吗？十分期待您的回复~

1.最优模型参数一般不是loss最低时的模型参数（可能已经过拟合了），一般是测试多个保存的模型参数，对比实验结果进行选择。
2.DFEW官方提供了5个划分子集。我们参考之前的工作，使用的是第一个划分，即DFEW_set_1_train.txt做训练集，DFEW_set_1_test.txt做测试集。没有做交叉验证。感谢您的提醒，我们后续将完善交叉验证的部分。

**Comment by qq1332427275** [comment]
您好，想再次了解一下关于模型的训练，关于MERR预训练时，发现coarse粒度的伪标签中并没有neutral fear disgust等，导致模型在此数据集上完整训练一轮后，在比如DFEW等下游数据集zero-shot评估时无法识别neutral等未被训练过的情感，您对DFEW zero-shot的checkpoint是基于什么训练得到的呢？训练方式是随机选取pseu_emotion/caption作为两个任务，是coarse训练后再经过fine-grained数据finetune吗，但finetune不是只使用smp_reason_caption进行推理任务吗，并没有pseu_emotion的情感分类任务训练。
还有一个疑惑是，您提到训练30个epoch，是将整个数据集完整训练30次吗？
期待您的回复！十分感谢！

**Comment by ZebangCheng** [comment]
1. 我们是在MERR数据集的coarse粒度部分数据上训练后，才进行DFEW等下游数据集zero-shot评估。coarse粒度的伪标签中有neutral类别的。
2. 我们在推理测试时发现，即使没有某些类别的标签进行训练，也能推理得到某些小众的类别标签。
3. 对于DFEW zero-shot的checkpoint是在coarse粒度数据上进行训练得到的，只训练单一的情绪识别任务，在进行推理测试时，修改了相关的prompt，将情绪类别标签扩展为DFEW包含的情绪类别：
> Please determine which emotion label in the video represents: happy, sad, neutral, angry, surprise, **disgust**, **fear**.
4. 训练30个epoch，不是将整个数据集完整训练30次。每个epoch我们设置的是5000个item，即每个epoch从数据集中随机选择5000个样本进行训练。对应的参数是`iters_per_epoch`
