### ISSUE TITLE
Data Selection Strategy

### ISSUE THREAD

**Issue by sjghh** [ZebangCheng/Emotion-LLaMA#14]
作者您好，想问一下从原始数据集到粗粒度，和从粗粒度到细粒度数据选择策略是什么？感谢您的回答

**Comment by ZebangCheng** [comment]
原始数据集到粗粒度数据集，我们是通过AU的组合是否与对应的情绪分类伪标签是否对应来进行筛选的。
从粗粒度到细粒度数据集，我们是通过人工筛选的。
