### ISSUE TITLE
MERR audio prompt

### ISSUE THREAD

**Issue by xiaoyaoxinyi** [ZebangCheng/Emotion-LLaMA#17]
Hello author, I would like to know what prompt you used for extracting audio information with qwen-audio. Thank you.

**Comment by xiaoyaoxinyi** [comment]
作者您好，在train_configs文件夹下的emotion-llama_finetune.yaml中，我看到了在run的参数下除了max_epoch还有iters_per_epoch被设置为1000，我想知道这个1000是什么意思，难道每轮训练的时候实际只使用了MERR数据集中的batch_size x iters_per_epoch的数据嘛

**Comment by ZebangCheng** [comment]
是的。iters_per_epoch参数的意思是就是每个epoch训练多少个样本的含义。每个epoch都会从所有的样本中随机抽取iters_per_epoch个样本进行训练，这样做的目的是为了避免过拟合。

我们的训练分为两部分， 在粗粒度训练时，iters_per_epoch设置为5000. 在细粒度训练时，iters_per_epoch设置为1000.
