### ISSUE TITLE
Reproduce experimental results

### ISSUE THREAD

**Issue by NLP-hua** [ZebangCheng/Emotion-LLaMA#18]
Hi, author,
How should I reproduce the experimental results in Table 2 of the paper? Could you provide the corresponding script?

**Comment by NLP-hua** [comment]
An other question is how to reproduce the performance of Table 1 of the paper?

**Comment by ZebangCheng** [comment]
We encountered some hardware issues while organizing the code. We plan to open source the related content by the end of October.

**Comment by NLP-hua** [comment]
Hello author. 
I noticed that some files were updated. But unfortunately, some files are empty. For example, Instruction_Tuning.md, eval_emotion_EMER.py, etc., uploaded last week. Is everything ok with u？

**Comment by ZebangCheng** [comment]
Yes, we prepared the relevant code files and documentation a week ago and successfully verified the code locally. However, the team member responsible for this part has recently encountered some urgent matters, so we need to wait for them to upload the content. Thank you for your understanding.
