### ISSUE TITLE
first_face.py问题

### ISSUE THREAD

**Issue by AbtMyML** [ZebangCheng/Emotion-LLaMA#28]
尊敬的作者，您好
您最近提交的first_face.py当中，我再运行评估的代码时遇到了AttributeError: 'FeatureFaceDataset' object has no attribute 'extract_frame' 问题，我想请问是不是first_face.py不完整

**Comment by ZebangCheng** [comment]
抱歉给你带来困扰，合并代码时遗漏了extract_frame函数，已补充上传。
感谢你的反馈。
