### ISSUE TITLE
关于ann_path的问题

### ISSUE THREAD

**Issue by fuyyyyy** [ZebangCheng/Emotion-LLaMA#30]
作者您好，想问一下下图中这几个txt文件具体指的是什么文件，方便提供一下吗？
<img width="638" alt="截屏2024-11-29 16 14 24" src="https://github.com/user-attachments/assets/ae8b9b60-12a5-44c9-bf07-76a77c272be5">
还有就是这几个文件分别指的是什么，在哪里需要使用呢？
<img width="299" alt="截屏2024-11-29 16 15 56" src="https://github.com/user-attachments/assets/0a5a9f61-2dc5-44e7-9814-0e24397658bb">
期待您的回复！

**Comment by fuyyyyy** [comment]
感谢您的回答！还有几个问题是：能否提供一下relative_train_NCEV.txt文件呢？以及featureface.yaml文件中image_path是不是只要把MER2023提供的视频全部放在对应这个文件夹里就可以？

**Comment by ZebangCheng** [comment]
在readme和其它issue中，有Google driver的链接。以下是项目相关Google driver链接，你可以在里面下载需要的文件：
> https://drive.google.com/drive/folders/1d-Sg5fAskt2s6OOEUNXFaM2u-C055Whj?usp=sharing

将image_path指向数据集的全部视频即可。

**Comment by fuyyyyy** [comment]
您好，我还想询问一些问题：
1. 关于 stage1 训练中 task_pool 选择，按照readme中写的是应该选择 "emotion" 和 "reason"，同时需要将ann_path选择为 MERR_coarse_grained.txt 对应的路径。但我在执行代码时因为 reason_json_file_path 指向的是 MERR_fine_grained.json 的文件导致了下面的报错，请问是我的路径设置有什么问题吗？
<img width="633" alt="截屏2024-12-03 23 16 09" src="https://github.com/user-attachments/assets/e7e81fc5-f586-4485-8062-462bca8226a6">
2. 在复现 MER2023 数据集上测试得到的结果是只需要用到 stage1 训练出来的 ckpt 吗？还是两个阶段训练完再去测试？
3. 我的训练过程中并没有使用 relative_train_NCEV.txt 文件，想问一下这个文件是不用被使用吗？

非常期待您的回答～

**Comment by fuyyyyy** [comment]
您好，我还想询问一些问题：
1. 关于 stage1 训练中 task_pool 选择，按照readme中写的是应该选择 "emotion" 和 "reason"，同时需要将ann_path选择为 MERR_coarse_grained.txt 对应的路径。但我在执行代码时因为 reason_json_file_path 指向的是 MERR_fine_grained.json 的文件导致了下面的报错，请问是我的路径设置有什么问题吗？
    caption = self.reason_dict[video_name]['smp_reason_caption']
KeyError: 'sample_00005561'

2. 在复现 MER2023 数据集上测试得到的结果是只需要用到 stage1 训练出来的 ckpt 吗？还是两个阶段训练完再去测试？ 
3. 我的训练过程中并没有使用 relative_train_NCEV.txt 文件，想问一下这个文件是不用被使用吗？

非常期待您的回答～

**Comment by ZebangCheng** [comment]
1. MERR_coarse_grained.json对应的键值是“caption”, MERR_fine_grained.json对应的键值是“smp_reason_caption”，键值不一样，导致不能正确获得情绪描述。
2. 我们是分粗粒度和细粒度训练了两次，然后选择分数最高的ckpt。
3. Emotion-LLaMA没有用到relative_train_NCEV.txt文件。relative_train_NCEV.txt（MER2023数据集训练集标签）是用于MER2023 baseline训练，然后给无标签的视频样本打伪标签，考虑到伪标签的分布与relative_train_NCEV.txt一致，就没有使用。
