### ISSUE TITLE
Issue about the minigptv2_checkpoint.pth

### ISSUE THREAD

**Issue by XuecWu** [ZebangCheng/Emotion-LLaMA#36]
Dear authors,

Thank you for your great work! Where can I find the minigptv2_checkpoint.pth?

Looking forward to your reply!

Thanks a lot!

**Comment by ZebangCheng** [comment]
I noticed that the official Google Drive download link appears to be invalid. Fortunately, the corresponding model parameters (minigptv2_checkpoint.pth) can still be downloaded from the Hugging Face Space:  

> https://huggingface.co/spaces/Vision-CAIR/MiniGPT-v2/tree/main
